language: node_js
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem install sass
- gem install compass
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli karma
- bower install
- "./node_modules/.bin/webdriver-manager update"
script:
- grunt test-e2e
- grunt test
after_success:
- grunt build
deploy:
  provider: divshot
  environment:
    master: development
    staging: staging
    production: production
  skip_cleanup: true
  api_key:
    secure: j1LdAEgPjMNM6rlSYdLjrlei3AYWkk9Rcoo7/8+znzS/c+yWpU28+NMGIoEU4cCrvrLKZfSuAZJzrnyFH7k6vWFBuOjKjfULj6BlABXdUsegZvlmaVrh2GyTLvnBNSVXS2tQiIIqADVWjujOSy5rXw4znPD8kqAnErTU27oPpNE=
